### ISSUE TITLE
안드로이드 예제 관련해서 질문 드립니다.

### ISSUE THREAD

**Issue by ddeokho** [nnsuite/nnstreamer-example#102]
안녕하세요.

안드로이드, NNStreamer-ssd 예제를 수정하며 공부 중 궁금한 것이 있어 질문을 남깁니다.

1. [nnstreamer-ex.cpp](https://github.com/nnsuite/nnstreamer-example/blob/master/android/example_app/nnstreamer-ssd/jni/nnstreamer-ex.cpp) 내의 파이프 라인을(507번째 줄) 바꾸어 카메라를 여는 것 대신 영상을 가지고 올 수 있도록 하려 합니다. 그리고 그 영상을 디텍션할 수는 없을까 고민하고 있습니다.

그래서 아래의 파이프 라인을 확인 후 해당 코드에 적용했습니다.
`sudo gst-launch-1.0 souphttpsrc location=http://aarkapp.iptime.org/aark_ob/test.webm ! decodebin ! autovideosink`

적용전
```
str_pipeline = g_strdup_printf
          (ahc2src ! videoconvert ! video/x-raw,format=RGB,width=640,height=480,framerate=30/1 ! tee name=traw "
```

적용 후

```
str_pipeline = g_strdup_printf
          ("uridecodebin uri=http://aarkapp.iptime.org/aark_ob/test.webm  ! decodebin ! tee name=traw "      
```

그 후 핸드폰에 빌드를 하니 "Failed to build pipeline [1]"와 같은 결과가 나옵니다. 파이프 라인이 잘못 적용된 거 같은데 파이프라인 외에도 변경해 주어야 할 게 있을 지 궁급합니다.

2. 위의 내용과 다른 질문입니다. 라이다의 실시간 데이터를 불러오려면 'appsrc'를 사용하면 된다고 알고 있습니다. NNStreamer 예제 중 카메라를 사용한 예제의 파이프라인 안에 'ahc2src' 또는 'v4l2src' 대신  'appsrc'로만 바꾸어 주면 되는 것일까요?

너무 기초적인 질문을 드려 죄송합니다. 혹시 제가 참고할 만한 것을 추천해 주셔도 좋습니다.
그리고 긴 글 읽어주셔서 감사합니다.

**Comment by myungjoo** [comment]
구체적인 에러메세지와 실행환경이 없으니 일반적인 답변 드립니다.
1. GStreamer는 20년쯤 된 시스템이라 구글검색하면 문서와 예제 매우 많습니다. (물론 한글로 검색하면 거의 없습니다.)
2. 사용하신 모든 플러그인 (Gstreamer plugin 포함) 이 실행환경에 모두 설치되어 있고 실행 가능한지 확인 하세요.
3. 만드신 파이프라인의 Capability 가 맞는지 확인하세요.
    - 일단 두 str_pipeline에서 보시면 윗쪽은 (적용 전) capability 변환을 해주는데, 아랫쪽은 안해줍니다. (videoconverter가 colorspace conversion을 해주며, caps-filter (```video/x-raw,format=RGB,width=640,height=480,framerate=30/1```) 에서 capability를 강제하고 있습니다. 아마 거기에 videorate, videoscale 같은것 까지 있으면 더 좋겠지요.
4. V4L2SRC는 Linux kernel의 v4l2로부터 읽어오는 것이고 appsrc는 App에서 Buffer를 Write합니다. 바꾼 다음 appsrc에 buffer write하는 코드는 만드셔야 겠지요.

**Comment by ddeokho** [comment]
감사합니다!

**Comment by ddeokho** [comment]
말씀해주신 문제는 해결했습니다! 감사합니다.
위에 말씀해 주신 4번과 실시간이 아닌 저장되어 있는 라이다 데이터를 불러오는 것이 궁금해서 입니다.

1. appsrc 고유의 코드를 바꾸어야 한다는 말씀이신지 터미널에 파이프라인을 넣을 때appsrc 뒤에 올 buffer 양을 조절하는 코드( 예 : ... ! queue leaky=2 max-size-buffers=10 ! ...)가 필요한 것인지 제가 이해를 잘못했습니다.

2. 실시간으로 읽어 오기 전 Kitti dataset의 lidar 데이터를 불러와 시험해 보려 합니다. 이에 .txt 형태로 저장되어 있는 라이다 데이터를 NNStreamer로 디텍션 하는 게 가능한지 궁금합니다. (제가 filesrc, multifilesrc 등으로 시도를 해보았는데 이미지, 영상은 불러와 지나 .txt는 못불러오더라고요..)

**Comment by myungjoo** [comment]
1. 둘 다 아닙니다. 파이프라인 자체를 잘 만드는 것에 더해 appsrc 에 데이터 넣는 부분을 만드셔야 합니다. 마음대로 넣을 데이터를 application에서 정해서 넣을 수 있어서 appsrc입니다.
2. .txt라고 안되는 것 아닙니다. tensor로 어떻게 encoding할지 정하셨으면 그에 따라 .txt를 잘 convert해주시면 됩니다. 단일 stream이면 그냥 filesrc쓰셔도 되고요. rawdata로 그대로 읽을 수 있으면 그대로 binary data로 읽어들이면 되고요. tensor로 가기전에 뭔가 포맷을 다시 정해야 하면 appsrc로 하고 file read, conversion을 app에서 한다음 해당 appsrc에 한 frame씩 밀어넣으면 됩니다.

**Comment by ddeokho** [comment]
자세히 답변해 주셔서 감사합니다. 해결해 보겠습니다.
