### ISSUE TITLE
nnstreamer-multi app cannot download model files on S8/S9/S10 devices.

### ISSUE THREAD

**Issue by leemgs** [nnsuite/nnstreamer-example#39]
It's strange. the nnstreamer-multi app cannot download model files on S8/S9/S10 devices.
You can download the application by searching "nnstreamer multi" at Google Store. 

* Debug message with adb/logcat:

![image](https://user-images.githubusercontent.com/82404/58921813-4a5b5880-8773-11e9-9714-c144b3889daf.png)

**Comment by leemgs** [comment]
I am going to fix this issue. 
So, I change the assignee from @jaeyung-jung to @leemgs.

**Comment by leemgs** [comment]
@myungjoo , @kparichay  Please try to use the below nnstreamer-multi application on our Android device. 

[nnstreamer-multi-release-20190605-1330.apk.tar.gz](https://github.com/nnsuite/nnstreamer-example/files/3255525/nnstreamer-multi-release-20190605-1330.apk.tar.gz)

**Comment by kparichay** [comment]
> @myungjoo , @kparichay Please try to use the below nnstreamer-multi application on our Android device.
> 
> * Fixed version:
>   [nnstreamer-multi-release-20190605-1330.apk.zip](https://github.com/nnsuite/nnstreamer-example/files/3255543/nnstreamer-multi-release-20190605-1330.apk.zip)

works on S10+
