### ISSUE TITLE
[Models] Improve get-model-* scripts to be more general

### ISSUE THREAD

**Issue by mojunsang26** [nnsuite/nnstreamer-example#64]
Currently, There are four scripts to get models in nnstreamer-example/bash_script/example_models. 

Could we use a single script that cover all the examples in the nnstreamer-exmaple repository.

How about 
```bash
$ ./get-model.sh image-classification-tflite
```

**Comment by myungjoo** [comment]
That'd be fine if you provide a proper "help" messages as well.
