### ISSUE TITLE
[Question] How to get labels.txt for example_image_classification_caffe2

### ISSUE THREAD

**Issue by mojunsang26** [nnsuite/nnstreamer-example#65]
There is following guidance in nnstreamer_example_image_classification_caffe2.c
```
 * Required model and resources are stored at below link
 * https://github.com/caffe2/models/tree/master/mobilenet_v2
```
But, I cannot find label.txt in the above link. How can I get label.txt file?
@wooksong

**Comment by myungjoo** [comment]
Because it's for ImageNet, label.txt should be the same with other models for ImageNet; e.g., mobilenet-v1.

**Comment by myungjoo** [comment]
Uh.. after testing it by yourself, you may update the guidance with a verified URL of working label.txt.
