### ISSUE TITLE
Is it possible to implement this code in Ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by Yonghuiii** [nnsuite/nnstreamer-example#97]
Hello,

I'm interested in deploy and develop this code in Android.

But, I have a different PC environment.

So I wonder that it is possible for me to implement this code in my Ubuntu 18.04 LTS environment.

Does it have some bugs or some issues when I implement this code in Ubuntu 18.04 LTS?

Please let me know it is possible or not.

Thank you:)

**Comment by Yonghuiii** [comment]
I already tested nnstreamer-example in Ubuntu 18.04 LTS!
It is going well!

**Comment by myungjoo** [comment]
As you already know, Ubuntu 18.04 is officially supported. In fact, it should work with any modern Linux distro. I use Ubuntu 18.04 at work as well. (some have even experimented nnstreamer in macOS and it worked.)

I'm closing this as you don't have problems anymore.

**Comment by Yonghuiii** [comment]
Thank you for your answer!

I will try to develop and contribute to nnnstreamer on mobile with lidar
sensor data.

and then, if it is possible, I will try to combine lidar sensor data with
other sensor data like RGB sensor.

It is kind of multi modal research.

So, as a first step of my research, I test nnstreamer android API in my
galaxy note8(arm64) environment.

Now I will study about nnstreamer Android API structure and try to apply
lidar sensor data in this API.

Two weeks ago, I sent email to you that if it possible to use lidar sensor
data in nnstreamer.

Your answer was that it is no problem which input data is used in
nnstreamer.

The important thing is the data type.

So, now I will find out how to use lidar sensor data in nnstreamer and how
to apply to it.

If I have questions and some issues, I will ask to github.

Thank you for your response!

From Yonghui hayley shim




2020년 1월 15일 (수) 오전 1:54, MyungJoo Ham <notifications@github.com>님이 작성:

**Comment by Yonghuiii** [comment]
Thank you for your answer!

I will try to develop and contribute to nnnstreamer on mobile with lidar
sensor data.

and then, if it is possible, I will try to combine lidar sensor data with
other sensor data like RGB sensor.

It is kind of multi modal research.

So, as a first step of my research, I test nnstreamer android API in my
galaxy note8(arm64) environment.

Now I will study about nnstreamer Android API structure and try to apply
lidar sensor data in this API.

Two weeks ago, I sent email to you that if it possible to use lidar sensor
data in nnstreamer.

Your answer was that it is no problem which input data is used in
nnstreamer.

The important thing is the data type.

So, now I will find out how to use lidar sensor data in nnstreamer and how
to apply to it.

If I have questions and some issues, I will ask to github.

Thank you for your response!

From Yonghui hayley shim

2020년 1월 15일 (수) 오전 1:54, MyungJoo Ham <notifications@github.com>님이 작성:
